# Site settings
title: restic
tagline: Backups done right!
description: Backups done right!
# this means to ignore newlines until "baseurl:"
# restic is a program that does backups right. IT's easy, fast, secure and
# efficient, and the backups are verifiable!
baseurl: "/"
url: "https://restic.github.io" # the base hostname & protocol for your site
language: en
blog_baseurl: "/blog/"

# put blog entries below the path '/blog'
permalink: /blog/:categories/:year-:month-:day/:title

# Build settings
markdown: kramdown

# enable GitHub Flavoured Markdown
kramdown:
  input: GFM
  hard_wrap: false
  math_engine_opts:
    preview: true
